AWSTemplateFormatVersion: '2010-09-09'

Description: Create a Resource without a Condition

Parameters:
  IncludesSubnet02:
    Description: Name of an active CloudFormation stack that contains "Core Infra" networking resources.
    Type: String
    Default: true

Conditions:
  IncludesSubnet02:
    Fn::Equals:
    - Ref: IncludesSubnet02
    - true

Mappings: {}

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24
  Subnet01:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/25
      VpcId: !Ref VPC
  Subnet02:
    Type: AWS::EC2::Subnet
    Condition: IncludesSubnet02
    Properties:
      CidrBlock: 10.0.0.128/25
      VpcId: !Ref VPC

Outputs: {}
