---
Description: creates an CloudFront Distribition with two buckets.
Mappings: {}
Outputs: {}
Parameters: {}
Resources:
  Bucket01:
    Type: AWS::S3::Bucket
  CloudFrontDistribition:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-defaultcachebehavior.html
        # this DefaultCacheBehavior sends all requests to Bucket01
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
          # question: does TargetOriginId need to match origin?
          TargetOriginId: Bucket01
          ViewerProtocolPolicy: allow-all
        Enabled: true
        Origins:
          - DomainName: !GetAtt [Bucket01, DomainName]
            # Id: is arbitrary
            Id: Bucket01
            S3OriginConfig: {}
