AWSTemplateFormatVersion: 2010-09-09
Description: Create an IAM user that can perform S3 bucket and object operations that do not allow potential data leaks.
Parameters:
  RestrictedIAMUserPassword:
    Type: String
    Description: AWS Console password for the IAM User
Mappings: {}
Resources:
  RestrictedIAMUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: !Ref RestrictedIAMUserPassword
      Path: /
      Policies:
      - PolicyName: RestrictedIAMPolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - s3:AbortMultipartUpload
            - s3:CreateBucket
            - s3:DeleteBucket
            # s3:DeleteBucketPolicy has been remove
            # s3:DeleteBucketPolicy
            # s3:DeleteBucketWebsite
            - s3:DeleteObject
            - s3:DeleteObjectVersion
            - s3:Get*
            - s3:List*
            #Y s3:PutAccelerateConfiguration
            # s3:PutBucketAcl can allow creation of an ACL allowing access outside of IAM
            # s3:PutBucketAcl
            # s3:PutBucketCORS allows CORS which should not be an issue with a private bucket
            # s3:PutBucketCORS
            # s3:PutBucketLogging
            # s3:PutBucketNotification
            # s3:PutBucketPolicy can allow creation of an Policy allowing access outside of IAM
            # s3:PutBucketPolicy
            # s3:PutBucketRequestPayment
            # s3:PutBucketRequestPayment
            # s3:PutBucketTagging
            # s3:PutBucketVersioning
            # s3:PutBucketWebsite does not set objects to public but it is 
            # s3:PutBucketWebsite
            # s3:PutLifecycleConfiguration allows transfer of data to other AWS resources
            # s3:PutLifecycleConfiguration
            # s3:PutReplicationConfiguration
            - s3:PutObject
            # s3:PutObjectAcl
            # s3:PutObjectVersionAcl
            # s3:ReplicateDelete
            # s3:ReplicateObject could allow replication of data into another AWS S3 Bucket
            # s3:ReplicateObject
            - s3:RestoreObject
            Resource: '*'
      UserName: RestrictedIAMUser
Outputs:
  # Note that outputting the password is not ideal outside of testing scenarios
  RestrictedIAMUserPassword:
    Description: AWS Console password for the IAM User
    Value: !Ref RestrictedIAMUserPassword
