AWSTemplateFormatVersion: '2010-09-09'

Description: Create a Resource without a Condition

Parameters:
  AZsSupportingSubnets:
    Description: Name of an active CloudFormation stack that contains "Core Infra" networking resources.
    Type: CommaDelimitedList
    Default: true

Mappings: {}

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24
  Subnet01:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select: 
          - 0
          - !Ref AZsSupportingSubnets
      CidrBlock: 10.0.0.0/25
      VpcId: !Ref VPC
  Subnet02:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select: 
          - 1
          - !Ref AZsSupportingSubnets
      CidrBlock: 10.0.0.128/25
      VpcId: !Ref VPC

Outputs: {}
