apiVersion: v1
kind: Pod
metadata:
  name: echo-node-hostname
spec:
  containers:
    - name: ubuntu
      image: ubuntu:latest
      env:
        # spec.nodeName available as part of: 
        # https://github.com/kubernetes/kubernetes/pull/27880
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      command: ['sh', '-c', "echo NODE_MAME is: $NODE_NAME."]
