---
AWSTemplateFormatVersion: '2010-09-09'

Description: Create a VPC containing four subnets and a Cisco ASA.

Parameters:

  # TODO: move to mappings, if this stack is used regularly
  CiscoASAvImageId:
    # https://aws.amazon.com/marketplace/server/configuration?productId=87868dac-850c-4c36-ba33-ff3d39a724ac
    Type: AWS::EC2::Image::Id
    Default: ami-7ae99f02
    Description: Cisco ASAv Image Id (AMI)

  CiscoASAvInstanceType:
    Type: String
    Description: Cisco ASAv Instance Type
    Default: c4.large
    AllowedValues:
      - c4.large

  CiscoASAvKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: ciscoasav
    Description: Cisco ASAv Key Name

Mappings: {}

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: Name
          Value: CiscoASAvVPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  PublicInternetRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicSubnetRouteTable

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PrivateSubnetRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicSubnetRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PrivateSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/26
      VpcId: !Ref VPC

  PrivateSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.64/26
      VpcId: !Ref VPC

  PublicSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.128/26
      VpcId: !Ref VPC

  PublicSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.192/26
      VpcId: !Ref VPC

  PrivateSubnet01RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateSubnetRouteTable
      SubnetId: !Ref PrivateSubnet01

  PrivateSubnet02RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateSubnetRouteTable
      SubnetId: !Ref PrivateSubnet02

  PublicSubnet01RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicSubnetRouteTable
      SubnetId: !Ref PublicSubnet01

  PublicSubnet02RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicSubnetRouteTable
      SubnetId: !Ref PublicSubnet02

  CiscoASAvSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Cisco ASAv Security Group
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 443
          ToPort: 443

  # TODO: move from AWS::EC2::EIP to NetworkInterfaces with AssociatePublicIpAddress: true
  CiscoASAvEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref CiscoASAvEC2Instance
      Domain: vpc

  CiscoASAvEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref CiscoASAvImageId
      InstanceType: !Ref CiscoASAvInstanceType
      KeyName: !Ref CiscoASAvKeyName
      SecurityGroupIds:
        - !Ref CiscoASAvSecurityGroup
      SubnetId: !Ref PublicSubnet01

Outputs: {}
