apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
    - name: ubuntu
      command: ["/bin/sleep", "3650d"]
      image: ubuntu:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: ubuntu-secret
          mountPath: /etc/secrets
  volumes:
    - name: ubuntu-secret
      secret:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        secretName: ubuntu-secret
