---

AWSTemplateFormatVersion: 2010-09-09

Description: Create all required resources to monitor for a given API call across all Regions

Conditions:

  CreateCloudTrail:
    # if the CreateCloudTrail parameter is "true" return "true"
    !Equals [ !Ref CreateCloudTrail, true] 

Parameters:

  CreateCloudTrail: 
    Type: String
    Default: false
    AllowedValues: 
      - true
      - false
    Description: Should a Global Services CloudTrail Trail be created? Only one should be created.

  RunInstancesEmailAddress: 
    Type: String
    Default: colin@cloudavail.com
    Description: Email Address that should be notified on "RunInstances" event.

Mappings: {}

Resources:

  # an S3 bucket is needed for writing CloudTrail events
  CloudTrailS3Bucket:
    # only create the CloudTrailS3Bucket if CreateCloudTrail is true
    Condition: CreateCloudTrail
    Type: AWS::S3::Bucket

  CloudTrailTrail:
    # only create the CloudTrailS3Bucket if CreateCloudTrail is true
    Condition: CreateCloudTrail
    Type: AWS::CloudTrail::Trail
    Properties:
      # EnableLogFileValidation
      EnableLogFileValidation: false
      # IncludeGlobalServiceEvents
      # Does CloudTrail include events generated by calls to global services
      # such as IAM?
      IncludeGlobalServiceEvents: true
      IsLogging: true
      # if IsMultiRegionTrail is true
      # then IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: true
      S3BucketName: !Ref CloudTrailS3Bucket

  # An S3 S3 Bucket Policy is required that allows the AWS CloudTrail service
  # to write to the S3 Bucket
  # Note that the use of a Bucket Policy in this CloudFormation file has
  # created intermittent issues where the CloudFormation Stack fails to build
  # ticket xxxxxxxx has been created with AWS regarding this issue
  CloudTrailS3BucketBucketPolicy:
    # only create the CloudTrailS3Bucket if CreateCloudTrail is true
    Condition: CreateCloudTrail
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref CloudTrailS3Bucket
      PolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - Effect: Allow
            Principal: 
              Service: cloudtrail.amazonaws.com
            Action:
              - s3:GetBucketAcl
            Resource:
              - !Sub "${CloudTrailS3Bucket.Arn}"
          - Effect: Allow
            Principal: 
              Service: cloudtrail.amazonaws.com
            Action:
              - s3:PutObject
            Resource:
              - !Sub "${CloudTrailS3Bucket.Arn}/AWSLogs/${AWS::AccountId}/*"
            Condition: 
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control

  RunInstancesSNSTopic: 
    Type: AWS::SNS::Topic
    Properties: 
      Subscription: 
        - Endpoint: !Ref RunInstancesEmailAddress
          Protocol: email

  # Resource-based policies are utilized for allowing CloudWatch Events
  # to invoke "targets" when given rules are violated
  # http://docs.aws.amazon.com/AmazonCloudWatch/latest/events/resource-based-policies-cwe.html
  RunInstancesSNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: RunInstancesSNSTopicPolicy
        Version: 2012-10-17
        Statement:
        - Sid: TrustCWEToPublishEventsToRunInstancesSNSTopic
          Effect: Allow
          Principal:
            Service: events.amazonaws.com
          Action: sns:Publish
          Resource: !Ref RunInstancesSNSTopic
      Topics:
        - !Ref RunInstancesSNSTopic

  RunInstanceEventsRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.ec2
        detail-type:
          # note that I have no evidence that CloudTrail
          # actually needs to be turned on
          - AWS API Call via CloudTrail
        detail: 
          eventSource: 
            - ec2.amazonaws.com
          eventName:
            - RunInstances
      # Note that State must be ENABLED or DISABLED, all capitals
      # 1 validation error detected: Value 'Enabled' at 'state' failed 
      # to satisfy constraint: Member must satisfy enum value set:
      # [ENABLED, DISABLED]
      State: ENABLED
      Targets:
        - Arn: !Ref RunInstancesSNSTopic
          Id: RunInstancesSNSTopic

Outputs: {}
