---

AWSTemplateFormatVersion: 2010-09-09

Resources:

  SingleKeyValueS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: '{{resolve:secretsmanager:/test/secret/singlekeyvalue:SecretString:username}}'

  MultiKeyValueS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: '{{resolve:secretsmanager:/test/secret/multikeyvalue:SecretString:username}}'

  MultiKeyValueS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: '{{resolve:secretsmanager:/test/secret/multikeyvalue:SecretString:password}}'
