---

AWSTemplateFormatVersion: 2010-09-09

Parameters: {}

Resources:

  SingleKeyValueSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /test/secret/singlekeyvalue
      SecretString: '{"username":"bob"}'


  MultiKeyValueSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /test/secret/multikeyvalue
      SecretString: '{"username":"bob", "password":"password"}'

Outputs: {}
