---

AWSTemplateFormatVersion: 2010-09-09

Description: Basic CloudFront CloudFormation

Parameters: {}

Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3.cloudavail.com

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
          TargetOriginId: S3Bucket
          ViewerProtocolPolicy: allow-all
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName: !GetAtt S3Bucket.DomainName
            CustomOriginConfig:
              HTTPPort: 80
              OriginProtocolPolicy: http-only
            Id: S3Bucket
