AWSTemplateFormatVersion: '2010-09-09'
Description: Create a VPC which will contain a Security Group that is created by another Stack.
Parameters: {}
Mappings: {}
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/24
      VpcId: !Ref VPC

Outputs:
  SharedVPCId:
    Description: the Shared VPC Id
    Value: !Ref VPC
    Export:
      Name: !Sub ${AWS::StackName}-VPCId